### ISSUE TITLE
Add spacing

### ISSUE THREAD

**Issue by markusi7** [ikocijan/MagicViews#17]
Hi Ivan, it would be cool to add a feature to change space between characters, something similiar to this"

<code>
public class SpacingTextView extends MagicTextView {

    private static final float NO_SPACING = 0.0f;

    private float letterSpacing = NO_SPACING;

    public SpacingTextView(Context context) {
        super(context);
        init();
    }

    public SpacingTextView(Context context, AttributeSet attrs) {
        super(context, attrs);
        getAttributes(attrs);
        init();
    }

    private void getAttributes(AttributeSet attrs) {
        if (attrs != null) {
            TypedArray a = getContext().obtainStyledAttributes(attrs, R.styleable.SpacingTextView, 0, 0);
            letterSpacing = a.getFloat(R.styleable.SpacingTextView_tv_spacing, 0);
            a.recycle();
        }
    }

    private void init() {
        final float THRESHOLD = 0.001f;
        if (Math.abs(letterSpacing - NO_SPACING) > THRESHOLD) {
            String originalText = getText().toString();
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < originalText.length(); i++) {
                String c = "" + originalText.charAt(i);
                builder.append(c.toLowerCase());
                if (i + 1 < originalText.length()) {
                    builder.append("\u00A0");
                }
            }

            SpannableString finalText = new SpannableString(builder.toString();
            if (builder.toString().length() > 1) {
                for (int i = 1; i < builder.toString().length(); i += 2) {
                    finalText.setSpan(new ScaleXSpan(letterSpacing), i, i + 1, Spannable.SPAN_INCLUSIVE_INCLUSIVE);
                }
            }

            setText(finalText, TextView.BufferType.SPANNABLE);
        }
    }
}
</code>

**Comment by ikocijan** [comment]
I finally had some time to check this out. It has been implemented and it will be available in 3.0.1. 

I did some changes and added regex since this implementation will fail if there is too much text. You can check MagicUtils class to see [my implementation.](https://github.com/ikocijan/MagicViews/blob/development/MagicViews/src/main/java/com/ivankocijan/magicviews/utils/MagicUtils.java)
