### ISSUE TITLE
MagicEditText does not acquire text color from textAppearance attribute

### ISSUE THREAD

**Issue by popmir** [ikocijan/MagicViews#19]
When style is set to textAppearance attribute the MagicEditText does not use the style to color text. Similar behavior is noted for EditText here: https://github.com/Prototik/HoloEverywhere/issues/730

**Comment by ikocijan** [comment]
I did some research regarding this but did not find anything useful. Since this library does not style Views like HoloEverywhere I can't use that fix. This issue is related to EditText not MagicViews. 

Closing this one.
