### ISSUE TITLE
Give access to "fontStyle" attribute

### ISSUE THREAD

**Issue by cartierjf** [ikocijan/MagicViews#3]
`fontStyle` should be accessible by either a getter or by being `protected`.
I am extending `MagicEditText` to override the `setError` method so I can use the custom type face on that one also. However the font to use is in `fontStyle`.

I tried using `FontUtils.getPrefFontStyle(context, attrs, PreferenceType.EDIT_TEXT_PREFERENCE);` in the constructor, but for a reason I don't know after calling the super constructor, this method always returns `null`. I guess `attrs` gets modified along the way...

**Comment by ikocijan** [comment]
Sorry for the late answer. 

Not sure if this is an issue or not. I have extended MagicEditText and everything works as expected. Closing this one.
