### ISSUE TITLE
Use the new AppCompat views which backport functionality

### ISSUE THREAD

**Issue by reisub** [ikocijan/MagicViews#8]
As per this blog post:
http://android-developers.blogspot.com/2015/04/android-support-library-221.html

There are new views which backport some cool stuff to pre-lollipop devices:
- AppCompatAutoCompleteTextView
- AppCompatButton
- AppCompatCheckBox
- AppCompatCheckedTextView
- AppCompatEditText
- AppCompatMultiAutoCompleteTextView
- AppCompatRadioButton
- AppCompatRatingBar
- AppCompatSpinner
- AppCompatTextView

We should extend these for a future MagicViews release.

**Comment by ikocijan** [comment]
3.0.0 release is out with support for AppCompat components.
